### PR TITLE
Support for building conda lib

### PR DESCRIPTION
**Pull request by denisoliveirac**

### CODE REVIEW

**Comment by mouradmourafiq** [comment]
Thanks for the PR I will look at it soon.

**Comment by mouradmourafiq** [comment]
FYI: I did not forget about this PR, I will make sure the packages are distributed on conda for the v0.5.

**Comment by denisoliveirac** [comment]
Any update?

**Comment by mouradmourafiq** [comment]
Hi @denisoliveirac I started some work, but unfortunately did not manage to make it for the v0.5. I was looking at feedstock to have an official distribution.

I will try to look at it in the next couple of days.

**Pull request closed without merging**
